// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 The rocket-userspace authors
/*
 * rk3576-mm-fp16-golden.c — regenerate tests/rk3576_mm_fp16_golden.h from charsiu.
 *
 * The RK3576 matmul-form fp16 program is charsiu's, transcribed. This prints what
 * charsiu's own code produces at every shape tests/rk3576_mm_fp16_gate.c runs, so the
 * gate's host half holds the transcription to its source rather than to itself:
 *
 *   - the register stream from charsiu_emit_job(), at four fixed addresses;
 *   - an FNV-1a hash of the coefficient buffer charsiu_build_coefs() writes, with the
 *     job fields charsiu's npu_fp16_test sets (zero bias and weight sums, zero points
 *     0, scales 1.0, acc_out);
 *   - an FNV-1a hash of a weight buffer placed through charsiu_w16_offset() in the
 *     GROUP layout, each (n, k) holding a 16-bit value hashed from its own index.
 *
 * Build it on any host against a charsiu checkout at 524e10a, with no CHARSIU_*
 * variable set (the emitter reads several):
 *
 *   gcc -O1 -std=gnu11 -I$CHARSIU/include tools/rk3576-mm-fp16-golden.c \
 *       $CHARSIU/src/job.c $CHARSIU/src/regcmd.c -lm -o golden
 *   ./golden > tests/rk3576_mm_fp16_golden.h
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "charsiu.h"

static const unsigned shapes[][3] = {
#include "../tests/rk3576_mm_fp16_shapes.h"
};

static uint64_t fnv(const uint8_t *p, size_t n)
{
	uint64_t h = 0xcbf29ce484222325ull;
	size_t i;

	for (i = 0; i < n; i++) { h ^= p[i]; h *= 0x100000001b3ull; }
	return h;
}

static uint16_t wval(unsigned n, unsigned k)
{
	uint32_t z = n * 0x9E3779B1u ^ (k + 0x7F4A7C15u) * 0x85EBCA77u;

	z ^= z >> 15; z *= 0x2C1B3C6Du; z ^= z >> 12;
	return (uint16_t)z;
}

int main(void)
{
	unsigned s, ns = sizeof shapes / sizeof shapes[0];

	printf("/* GENERATED by tools/rk3576-mm-fp16-golden.c from charsiu 524e10a. Do not edit. */\n");
	printf("#define RK3576_MM_FP16_GOLDEN_IN   0x11000000u\n");
	printf("#define RK3576_MM_FP16_GOLDEN_W    0x33000000u\n");
	printf("#define RK3576_MM_FP16_GOLDEN_OUT  0x22000000u\n");
	printf("#define RK3576_MM_FP16_GOLDEN_COEF 0x44000000u\n");
	printf("static const struct { unsigned m, k, n; unsigned long long coef_fnv, w_fnv; "
	       "unsigned coef_bytes; unsigned long long ops[148]; } rk3576_mm_fp16_golden[] = {\n");
	for (s = 0; s < ns; s++) {
		struct charsiu_job job = { 0 };
		uint64_t ops[512];
		size_t nreg, i, cb, wb;
		uint8_t *coef, *w;
		int32_t *zero;
		unsigned n, k;

		job.cbuf_window = (unsigned)charsiu_cbuf_window();
		job.mm.m = shapes[s][0]; job.mm.k = shapes[s][1]; job.mm.n = shapes[s][2];
		job.mm.wdtype = CHARSIU_FP16; job.mm.adtype = CHARSIU_FP16;
		job.input_scale = job.weight_scale = job.output_scale = 1.0f;
		job.acc_out = 1;
		job.input_addr = 0x11000000u; job.weight_addr = 0x33000000u;
		job.output_addr = 0x22000000u; job.coef_addr = 0x44000000u;
		nreg = charsiu_emit_job(&job, ops, 512);
		if (nreg != 148) { fprintf(stderr, "%zu words, not 148\n", nreg); return 1; }

		cb = charsiu_coef_bytes(&job.mm);
		coef = malloc(cb); zero = calloc(job.mm.n, sizeof(int32_t));
		charsiu_build_coefs(&job, zero, zero, coef);

		wb = charsiu_weight_bytes(&job.mm);
		w = calloc(1, wb);
		for (n = 0; n < job.mm.n; n++)
			for (k = 0; k < job.mm.k; k++) {
				size_t off = charsiu_w16_offset(&job.mm, n, k, CHARSIU_W16_GROUP);
				uint16_t v = wval(n, k);
				w[off] = (uint8_t)(v & 0xff); w[off + 1] = (uint8_t)(v >> 8);
			}

		printf("  { %u, %u, %u, 0x%016llxull, 0x%016llxull, %zu, {", job.mm.m, job.mm.k,
		       job.mm.n, (unsigned long long)fnv(coef, cb), (unsigned long long)fnv(w, wb), cb);
		for (i = 0; i < nreg; i++)
			printf("%s0x%016llxull", !i ? "\n    " : i % 4 ? ", " : ",\n    ",
			       (unsigned long long)ops[i]);
		printf(" } },\n");
		free(coef); free(zero); free(w);
	}
	printf("};\n");
	return 0;
}
